---
  - name: Create Gluster cluster
    hosts: gluster_servers
    become: True
    #gather_facts: false
    vars:
      # Gluster configuration.
      gluster_mount_dir: /mnt/gluster
      gluster_brick_dir: /srv/gluster/brick
      gluster_brick_name: gluste
    roles:
      - geerlingguy.glusterfs
      - mgmt-hosts

    tasks:
      - name: Ensure Gluster brick and mount directories exist.
        file: "path={{ item }} state=directory mode=0775"
        with_items:
          - "{{ gluster_brick_dir }}"
          - "{{ gluster_mount_dir }}"
  
      - name: Configure Gluster volume.
        gluster_volume:
          state: present
          name: "{{ gluster_brick_name }}"
          brick: "{{ gluster_brick_dir }}"
          replicas: 4
          cluster: "{{ groups.gluster_servers | join(',') }}"
          host: "{{ inventory_hostname }}"
          force: yes
        run_once: true
  
      - name: Ensure Gluster volume is mounted.
        mount:
          name: "{{ gluster_mount_dir }}"
          src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
          fstype: glusterfs
          opts: "defaults,_netdev"
          state: mounted