

- name: Remove ansible_hostname from the line 127.0.0.1
  replace:
    path: /etc/hosts
    regexp: "127[.]0[.]0[.]1(.*){{ ansible_hostname }}(.*)"
    replace: '127.0.0.1 \1 \2'

- name: Remove line 127.0.0.1 without hostname
  lineinfile:
    dest: /etc/hosts
    regexp: "127[.]0[.]0[.]1( |\t)*$"
    state: absent
    
# - name: add hostname to /etc/hosts
#   vars:
#     comment: '# added by ansible'
#   replace:
#     path: /etc/hosts
#     regexp: "127[.]0[.]0[.]1 (?!localhost.localdomain localhost {{ ansible_hostname }})"
#     replace: "127.0.0.1 localhost.localdomain localhost {{ ansible_hostname }} "
#     #line: "127.0.0.1 localhost.localdomain localhost {{ ansible_hostname }} {{ comment }}"
#     backup: yes

# - name: add IP address of all hosts to /etc/hosts
#   vars:
#     comment: '# added by ansible'
#   lineinfile:
#     dest: /etc/hosts
#     regexp: ".* {{ item }} {{ comment }}"
#     line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }} {{ comment }}"
#     state: present
#     backup: yes
#   when: ansible_hostname != item
#   loop: "{{ query('inventory_hostnames', 'all') }}"

# - debug:
#     msg: "{{ hostvars[item] ['ansible_all_ipv4_addresses'] | type_debug }} {{ item }} "
#   when: ansible_hostname != item
#   loop: "{{ query('inventory_hostnames', 'all') }}"

# - name: test
#   vars: 
#     ipfilter: 192.168
#   debug:
#     msg: "{{ hostvars[item]['ansible_all_ipv4_addresses'] | select('match', '192.168') | list | join('') }} {{ item }} "
#   when: ansible_hostname != item
#   loop: "{{ query('inventory_hostnames', 'all') }}"


# - name: Add IP address of all hosts to all hosts
#   vars: 
#     ipfilter: "192.168"
#   lineinfile:
#     dest: /etc/hosts
#     regexp: '^(.*){{ item }}[ ](.*)$'
#     line: '{{ hostvars[item]["ansible_all_ipv4_addresses"] | select("match", ipfilter) | list | join("") }} {{ item }}'
#     state: present
#   when: ansible_hostname != item
#   loop: "{{ query('inventory_hostnames', 'all') }}"


# - name: Add IP address of all hosts to all hosts
#   replace:
#     path: /etc/hosts
#     regexp: '(\s+){{ item }}\s?(?!{{ alias_hosts[item] | join(" ") }})$'
#     replace: '\1{{item}} {{alias_hosts[item] | join(" ") }}'
#   when: alias_hosts[item] is defined
#   loop: "{{ query('inventory_hostnames', 'all') }}"

- name: Add IP address of all hosts to all hosts
  vars: 
    ipfilter: "192.168"
  lineinfile:
    dest: /etc/hosts
    regexp: '^(.*){{ item }}[ ](.*)$'
    line: '{{ hostvars[item]["ansible_all_ipv4_addresses"] | select("match", ipfilter) | list | join("") }} {{ item }} {{alias_hosts[item]| default("") | join(" ") }}'
    state: present
  loop: "{{ query('inventory_hostnames', 'all') }}"